### PR TITLE
Fix MemberID and GroupIDs are mixed

### PR DESCRIPTION
**Pull request by t3hn0**
Fix for issue #57

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
@t3hno Thanks for taking the time to contribute back to the project.

Could you add some unit test to cover the scenario you are trying to fix?

Also, I see that your PR is targeting the `3` branch. That's the branch that will be used to create our next minor release.

For this kind of bug fix, you can target the current "patch release" branch. This means that your fix will be available right away on merge.

**Comment by GuySartorelli** [comment]
@t3hn0 Are you still interesting in having this change merged in? If so, can you please respond to the above request for changes?

**Comment by GuySartorelli** [comment]
I think this PR is just wrong - the current unit tests check that the appropriate logging is done. This PR breaks those tests, which are currently passing on the `3` and `3.0` branches.

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
There's two classes:
- `AuditHookMemberGroupSet` that overrides [Member_GroupSet](https://github.com/silverstripe/silverstripe-framework/blob/358cbc9ee56ff70cd50342746082ff07c7c2bf0b/src/Security/Member_GroupSet.php)
- `AuditHookManyManyList` that overrides [ManyManyList](https://github.com/silverstripe/silverstripe-framework/blob/358cbc9ee56ff70cd50342746082ff07c7c2bf0b/src/ORM/ManyManyList.php)

When you call `$member->Groups()`, you get a `AuditHookMemberGroupSet`. When you call `$group->Members()`, you get a `AuditHookManyManyList`.

The updated code in this PR is only reached when you try remove a member from the Member list of a group.

```php
$group->Members()->removeByID($myMemberID);
```

In this context, `$itemID` will be the ID of a member. The original code is behaving as expected. `$itemID` is uesed to fetch the Member and `$this->getForeignID()` is used to fetch the Group.

`AuditHookMemberGroupSet` correctly does the reverse.

**Comment by maxime-rainville** [comment]
PR introduces the problem its trying to fix.

**Pull request closed without merging**
