### PR TITLE
DEP Use the canonical repository for proxy-db

### PR DESCRIPTION
**Pull request by GuySartorelli**
Requires https://github.com/tractorcow/silverstripe-proxy-db/pull/6 to be merged and tagged

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/658

### CODE REVIEW

**Review by emteknetnz — APPROVED** [review]
Approved but don't merge until https://github.com/tractorcow/silverstripe-proxy-db/pull/6 is merged

**Comment by emteknetnz** [comment]
@GuySartorelli can you re push this to get a new build to run

**Comment by GuySartorelli** [comment]
@emteknetnz I can but shouldn't we wait for proxy-db to be tagged stable?

**Comment by jareddreyerss** [comment]
@GuySartorelli we got 2.0.0 stable tag today, can we get this merged when next possible please ❤️

**Comment by GuySartorelli** [comment]
Rebased and retargetted to `3.1`

**Review by michalkleiner — APPROVED** [review]

**Comment by michalkleiner** [comment]
This needs to be backported to 3.0 as well, will open a PR.

**Pull request merged**
