### PR TITLE
[WIP] Add logging hooks for MFA

### PR DESCRIPTION
**Pull request by Firesphere**
Related: https://github.com/Firesphere/silverstripe-bootstrapmfa/pull/54

- Hook in the MFA login process when Bootstrap MFA module is installed
- Log all actions as info or warning to the selected logger

### CODE REVIEW

**Comment by Firesphere** [comment]
Travis-CI breaking seems to be unrelated

**Comment by ScopeyNZ** [comment]
Ah the builds are failing when they're not using either the latest development head or they're using `recipe-core`. For now we can probably just set the builds to use `recipe-cms` only.

**Comment by robbieaverill** [comment]
I'll fix that in the upstream branch (https://github.com/silverstripe/silverstripe-auditor/pull/28)

**Comment by robbieaverill** [comment]
@Firesphere FYI I've rebased this branch onto the latest master

**Review by robbieaverill — COMMENTED** [review]
Looking good! I think it might be worth replacing "MFA" with "multi factor authentication" since this isn't an MFA module, good to be explicit.

Also would be good to update the unit tests to include these new hooks

**Comment by Firesphere** [comment]
@robbieaverill The tests are the reason it's marked as WIP :)

**Comment by robbieaverill** [comment]
Just noting that we want to keep this PR around, we'll get to picking it up eventually to help finish it off @Firesphere

**Comment by robbieaverill** [comment]
Thanks for the PR! I've just had a bit of a review and compared against what we're going to be implementing in silverstripe/mfa and there's a few things here that we won't need, so I'm going to close it for now. Cheers though!

**Pull request closed without merging**
